// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeG1y2E857D6JEOFbRouhSdS24uJw1pjc',
    appId: '1:594062082895:web:5bce083ee71e3668e43b3a',
    messagingSenderId: '594062082895',
    projectId: 'social-app-12055',
    authDomain: 'social-app-12055.firebaseapp.com',
    storageBucket: 'social-app-12055.appspot.com',
    measurementId: 'G-9C6C718Y83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQefb6Tg5fNGLqyzonpBn5dtS_xz0gpMY',
    appId: '1:594062082895:android:4055fc3c6be30186e43b3a',
    messagingSenderId: '594062082895',
    projectId: 'social-app-12055',
    storageBucket: 'social-app-12055.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Fq9sncd7Pwyp09S1r-2TdjP1hTJbZGY',
    appId: '1:594062082895:ios:e9b3a0d605ceba12e43b3a',
    messagingSenderId: '594062082895',
    projectId: 'social-app-12055',
    storageBucket: 'social-app-12055.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static  FirebaseOptions macos = const FirebaseOptions(
    apiKey: 'AIzaSyD3Fq9sncd7Pwyp09S1r-2TdjP1hTJbZGY',
    appId: '1:594062082895:ios:042fba6556f71a2ee43b3a',
    messagingSenderId: '594062082895',
    projectId: 'social-app-12055',
    storageBucket: 'social-app-12055.appspot.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
